### ISSUE TITLE
Resizing asset limits

### ISSUE THREAD

**Issue by WantedDV** [approved/T7Zeus#1]
I am able to load the dll and it gets initialized, however resizing asset limits does not seem to work. Despite adding `zeus::Game::ResizeAssetLimits(zeus::XAssetType::Attachment, 256);` to dllmain I still get this error:

![image](https://github.com/approved/T7Zeus/assets/122710241/d37099a0-3922-4ba6-bf4f-ef515f3670ec)

Could you upload a minimal working mod template that demonstrates asset resizing?

**Comment by approved** [comment]
Unfortunately, this is a result of the code being run _after_ the assets have been loaded. I have been meaning to provide a way for this to be possible, maybe by a requirements file or a similar system that will be checked for before loading any other assets.

For now, the best solution is to install the dll in your BO3 root folder so it's loaded on startup. You will need to proxy a dll for this to work. I would recommend `WindowsCodecs.dll`. If you need help with this, you can message me on discord: `approved`

I'll leave this issue open until I resolve a way for it to be done via scripting
